name: 'adventureworks_analytics'
version: '1.0.0'
profile: 'adventureworks_analytics'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:  
  - "target"
  - "dbt_packages"
models:
  adventureworks_analytics:
    # 🥈 Silver Layer: Materializes everything in models/staging as views in 'silver'
    staging:
      +materialized: view
    # 🥇 Gold Layer: Materializes everything in models/marts as tables in a custom 'gold' schema
    marts:
      +materialized: table
      +schema: gold_adventureworks
